### ISSUE TITLE
Can we get a version of this code for identity vault without ngrx

### ISSUE THREAD

**Issue by fitprotracker** [ionic-enterprise/tea-taster-angular#1]
Hello,

We took our first stab at publishing our Identity vault into production but having issues, which means our use of Identity Vault workflow is probably not implemented correctly. 

I am coming back to ground zero in making sure I understand Identity Vault, however, in trying to look and understand the code, it is confusing with the Ngrx code in there since we have not used that, and is too complicated. 

I would like to learn and use a walkthrough with the basic user login and vault logic without the need to learn ngrx.  

Thanks

Antonio

**Comment by kensodemann** [comment]
This repo is meant to the be result of our three-day training, which includes training in using a state management system, in this case NgRX. NgRX is part of the Angular training as many of our Enterprise customers who are using Angular have expressed interest in knowing about it given the general complexity of an Enterprise level app and the related problems that NgRX solves. As such, it will have NgRX included.

There are a couple of other sample applications that do not have NgRX included, such as:

- https://github.com/ionic-enterprise/simple-iv-ng
- https://github.com/ionic-enterprise/tea-taster-vue (this is Vue, but the basic logic would be the same, just the mechanics of creating the services would be different)
- https://github.com/ionic-team/ionifits

For the best support, please create a ticket over at https://ionic.zendesk.com/. This will allow you to get in touch with a Solutions Architect to help review your implementation with you.
